/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author edson
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
    }

    public JTable getTable() {
        return jTable1;
    }

    public void setTable(JTable jTable1) {
        this.jTable1 = jTable1;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollTabelaAgenda = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAgendar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextValor = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        jLabelObservacoes = new javax.swing.JLabel();
        jLabelTitleAgenda = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jComboServico = new javax.swing.JComboBox<>();
        jComboBoxNome = new javax.swing.JComboBox<>();
        jLabelPainelAgenda = new javax.swing.JLabel();
        jLabelFundoAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Cliente", "Valor"
            }
        ));
        jScrollTabelaAgenda.setViewportView(jTable1);

        getContentPane().add(jScrollTabelaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 690, 1030, 300));

        jButtonAgendar.setBackground(new java.awt.Color(144, 238, 144));
        jButtonAgendar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.setAlignmentY(0.0F);
        jButtonAgendar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 550, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 550, 250));
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 280, 40));
        getContentPane().add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 280, 40));

        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 280, 40));

        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 280, 40));

        jLabelObservacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelObservacoes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacoes.setText("Observações");
        getContentPane().add(jLabelObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        jLabelTitleAgenda.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelTitleAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleAgenda.setText("Agenda");
        getContentPane().add(jLabelTitleAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        jLabelHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, -1, -1));

        jLabelData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        jLabelValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jLabelServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Serviço");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabelId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("Id");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jComboServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 280, 40));

        getContentPane().add(jComboBoxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 280, 40));

        jLabelPainelAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPainelAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbershop/view/img/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabelFundoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barbershop/view/img/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHoraActionPerformed

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jComboServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboServicoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboServicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboBoxNome;
    private javax.swing.JComboBox<String> jComboServico;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFundoAgenda;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelObservacoes;
    private javax.swing.JLabel jLabelPainelAgenda;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelTitleAgenda;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollTabelaAgenda;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
    }

    public JComboBox<String> getjComboBoxNome() {
        return jComboBoxNome;
    }

    public void setjComboBoxNome(JComboBox<String> jComboBoxNome) {
        this.jComboBoxNome = jComboBoxNome;
    }

    public JComboBox<String> getjComboServico() {
        return jComboServico;
    }

    public void setjComboServico(JComboBox<String> jComboServico) {
        this.jComboServico = jComboServico;
    }

    public JTextField getjTextValor() {
        return jTextValor;
    }

    public void setjTextValor(JTextField jTextValor) {
        this.jTextValor = jTextValor;
    }
    
    
}
